FROM python:3.11-slim

COPY --from=ghcr.io/astral-sh/uv:0.4.0 /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml .
COPY uv.lock .

RUN uv sync --frozen --no-dev

COPY . .

ENV PATH="/app/.venv/bin:$PATH"

ENV PORT=8080
EXPOSE 8080

CMD ["streamlit", "run", "ui/streamlit_app.py", "--server.port", "8080", "--server.address", "0.0.0.0"]
